In [22]:
import pandas as pd
import numpy as np

In [23]:

data = pd.read_csv("car_dataset.csv")

In [24]:
data.columns

Index(['3', '?', 'alfa-romero', 'gas', 'std', 'two', 'convertible', 'rwd',
       'front', '88.60', '168.80', '64.10', '48.80', '2548', 'dohc', 'four',
       '130', 'mpfi', '3.47', '2.68', '9.00', '111', '5000', '21', '27',
       '13495'],
      dtype='object')

In [25]:
data["fuel-type"].sum()

KeyError: 'fuel-type'

In [26]:
data.info

<bound method DataFrame.info of      3    ?  alfa-romero     gas    std   two  convertible  rwd  front  88.60  \
0    3    ?  alfa-romero     gas    std   two  convertible  rwd  front   88.6
1    1    ?  alfa-romero     gas    std   two    hatchback  rwd  front   94.5
2    2  164         audi     gas    std  four        sedan  fwd  front   99.8
3    2  164         audi     gas    std  four        sedan  4wd  front   99.4
4    2    ?         audi     gas    std   two        sedan  fwd  front   99.8
..  ..  ...          ...     ...    ...   ...          ...  ...    ...    ...
199 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
200 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1
201 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
202 -1   95        volvo  diesel  turbo  four        sedan  rwd  front  109.1
203 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1

     ...  130  mpfi  3.47  2.68  9.00  111  5000  21  27  13495
0    ...  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500
1    ...  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500
2    ...  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950
3    ...  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450
4    ...  136  mpfi  3.19  3.40   8.5  110  5500  19  25  15250
..   ...  ...   ...   ...   ...   ...  ...   ...  ..  ..    ...
199  ...  141  mpfi  3.78  3.15   9.5  114  5400  23  28  16845
200  ...  141  mpfi  3.78  3.15   8.7  160  5300  19  25  19045
201  ...  173  mpfi  3.58  2.87   8.8  134  5500  18  23  21485
202  ...  145   idi  3.01  3.40  23.0  106  4800  26  27  22470
203  ...  141  mpfi  3.78  3.15   9.5  114  5400  19  25  22625

[204 rows x 26 columns]>

In [27]:
data.head

<bound method NDFrame.head of      3    ?  alfa-romero     gas    std   two  convertible  rwd  front  88.60  \
0    3    ?  alfa-romero     gas    std   two  convertible  rwd  front   88.6
1    1    ?  alfa-romero     gas    std   two    hatchback  rwd  front   94.5
2    2  164         audi     gas    std  four        sedan  fwd  front   99.8
3    2  164         audi     gas    std  four        sedan  4wd  front   99.4
4    2    ?         audi     gas    std   two        sedan  fwd  front   99.8
..  ..  ...          ...     ...    ...   ...          ...  ...    ...    ...
199 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
200 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1
201 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
202 -1   95        volvo  diesel  turbo  four        sedan  rwd  front  109.1
203 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1

     ...  130  mpfi  3.47  2.68  9.00  111  5000  21  27  13495
0    ...  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500
1    ...  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500
2    ...  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950
3    ...  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450
4    ...  136  mpfi  3.19  3.40   8.5  110  5500  19  25  15250
..   ...  ...   ...   ...   ...   ...  ...   ...  ..  ..    ...
199  ...  141  mpfi  3.78  3.15   9.5  114  5400  23  28  16845
200  ...  141  mpfi  3.78  3.15   8.7  160  5300  19  25  19045
201  ...  173  mpfi  3.58  2.87   8.8  134  5500  18  23  21485
202  ...  145   idi  3.01  3.40  23.0  106  4800  26  27  22470
203  ...  141  mpfi  3.78  3.15   9.5  114  5400  19  25  22625

[204 rows x 26 columns]>

In [28]:
data.tail

<bound method NDFrame.tail of      3    ?  alfa-romero     gas    std   two  convertible  rwd  front  88.60  \
0    3    ?  alfa-romero     gas    std   two  convertible  rwd  front   88.6
1    1    ?  alfa-romero     gas    std   two    hatchback  rwd  front   94.5
2    2  164         audi     gas    std  four        sedan  fwd  front   99.8
3    2  164         audi     gas    std  four        sedan  4wd  front   99.4
4    2    ?         audi     gas    std   two        sedan  fwd  front   99.8
..  ..  ...          ...     ...    ...   ...          ...  ...    ...    ...
199 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
200 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1
201 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
202 -1   95        volvo  diesel  turbo  four        sedan  rwd  front  109.1
203 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1

     ...  130  mpfi  3.47  2.68  9.00  111  5000  21  27  13495
0    ...  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500
1    ...  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500
2    ...  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950
3    ...  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450
4    ...  136  mpfi  3.19  3.40   8.5  110  5500  19  25  15250
..   ...  ...   ...   ...   ...   ...  ...   ...  ..  ..    ...
199  ...  141  mpfi  3.78  3.15   9.5  114  5400  23  28  16845
200  ...  141  mpfi  3.78  3.15   8.7  160  5300  19  25  19045
201  ...  173  mpfi  3.58  2.87   8.8  134  5500  18  23  21485
202  ...  145   idi  3.01  3.40  23.0  106  4800  26  27  22470
203  ...  141  mpfi  3.78  3.15   9.5  114  5400  19  25  22625

[204 rows x 26 columns]>

In [29]:
data.iloc[0:10]

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
5,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
6,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
7,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
8,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430

In [30]:
data.loc[0:10, ["horsepower","price"]]

KeyError: "None of [Index(['horsepower', 'price'], dtype='object')] are in the [columns]"

In [ ]:
data[((data["make"]=="toyota") & (data["engine-location"]=="front")) | (data["body-style"] == "sedan")]

In [31]:
data.isna().sum

<bound method DataFrame.sum of          3      ?  alfa-romero    gas    std    two  convertible    rwd  \
0    False  False        False  False  False  False        False  False
1    False  False        False  False  False  False        False  False
2    False  False        False  False  False  False        False  False
3    False  False        False  False  False  False        False  False
4    False  False        False  False  False  False        False  False
..     ...    ...          ...    ...    ...    ...          ...    ...
199  False  False        False  False  False  False        False  False
200  False  False        False  False  False  False        False  False
201  False  False        False  False  False  False        False  False
202  False  False        False  False  False  False        False  False
203  False  False        False  False  False  False        False  False

     front  88.60  ...    130   mpfi   3.47   2.68   9.00    111   5000  \
0    False  False  ...  False  False  False  False  False  False  False
1    False  False  ...  False  False  False  False  False  False  False
2    False  False  ...  False  False  False  False  False  False  False
3    False  False  ...  False  False  False  False  False  False  False
4    False  False  ...  False  False  False  False  False  False  False
..     ...    ...  ...    ...    ...    ...    ...    ...    ...    ...
199  False  False  ...  False  False  False  False  False  False  False
200  False  False  ...  False  False  False  False  False  False  False
201  False  False  ...  False  False  False  False  False  False  False
202  False  False  ...  False  False  False  False  False  False  False
203  False  False  ...  False  False  False  False  False  False  False

        21     27  13495
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False
4    False  False  False
..     ...    ...    ...
199  False  False  False
200  False  False  False
201  False  False  False
202  False  False  False
203  False  False  False

[204 rows x 26 columns]>

In [32]:
data.isnull().sum()

3              0
?              0
alfa-romero    0
gas            0
std            0
two            0
convertible    0
rwd            0
front          0
88.60          0
168.80         0
64.10          0
48.80          0
2548           0
dohc           0
four           0
130            0
mpfi           0
3.47           0
2.68           0
9.00           0
111            0
5000           0
21             0
27             0
13495          0
dtype: int64

In [33]:
data.dtypes

3                int64
?               object
alfa-romero     object
gas             object
std             object
two             object
convertible     object
rwd             object
front           object
88.60          float64
168.80         float64
64.10          float64
48.80          float64
2548             int64
dohc            object
four            object
130              int64
mpfi            object
3.47            object
2.68            object
9.00           float64
111             object
5000            object
21               int64
27               int64
13495           object
dtype: object

In [34]:
data["price"] = data["price"].replace("?",np.nan)

KeyError: 'price'

In [35]:
data["price"] = data["price"].astype("float64")

KeyError: 'price'

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   3            204 non-null    int64
 1   ?            204 non-null    object
 2   alfa-romero  204 non-null    object
 3   gas          204 non-null    object
 4   std          204 non-null    object
 5   two          204 non-null    object
 6   convertible  204 non-null    object
 7   rwd          204 non-null    object
 8   front        204 non-null    object
 9   88.60        204 non-null    float64
 10  168.80       204 non-null    float64
 11  64.10        204 non-null    float64
 12  48.80        204 non-null    float64
 13  2548         204 non-null    int64
 14  dohc         204 non-null    object
 15  four         204 non-null    object
 16  130          204 non-null    int64
 17  mpfi         204 non-null    object
 18  3.47         204 non-null    object
 19  2.68         204 non-null    object
 20  9.00         204 non-null    float64
 21  111          204 non-null    object
 22  5000         204 non-null    object
 23  21           204 non-null    int64
 24  27           204 non-null    int64
 25  13495        204 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB

In [37]:
data["peak-rpm"] = data["peak-rpm"].replace("?",np.nan)

KeyError: 'peak-rpm'

In [38]:
data["peak-rpm"] = data["peak-rpm"].astype("float64")

KeyError: 'peak-rpm'

In [39]:
data.to_csv("car_dataset_cleaned.csv", index=False)

In [40]:
data["price"]

KeyError: 'price'

In [41]:
[data["price"].isnull()]

KeyError: 'price'

In [42]:
data[data.isnull().all(axis=1)]

Empty DataFrame
Columns: [3, ?, alfa-romero, gas, std, two, convertible, rwd, front, 88.60, 168.80, 64.10, 48.80, 2548, dohc, four, 130, mpfi, 3.47, 2.68, 9.00, 111, 5000, 21, 27, 13495]
Index: []

[0 rows x 26 columns]

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   3            204 non-null    int64
 1   ?            204 non-null    object
 2   alfa-romero  204 non-null    object
 3   gas          204 non-null    object
 4   std          204 non-null    object
 5   two          204 non-null    object
 6   convertible  204 non-null    object
 7   rwd          204 non-null    object
 8   front        204 non-null    object
 9   88.60        204 non-null    float64
 10  168.80       204 non-null    float64
 11  64.10        204 non-null    float64
 12  48.80        204 non-null    float64
 13  2548         204 non-null    int64
 14  dohc         204 non-null    object
 15  four         204 non-null    object
 16  130          204 non-null    int64
 17  mpfi         204 non-null    object
 18  3.47         204 non-null    object
 19  2.68         204 non-null    object
 20  9.00         204 non-null    float64
 21  111          204 non-null    object
 22  5000         204 non-null    object
 23  21           204 non-null    int64
 24  27           204 non-null    int64
 25  13495        204 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB

In [2]:
data[fuel-type] == "diesel"

NameError: name 'data' is not defined